version: '3'
services:
  postgresdb:
    image: 'postgres'
    container_name: 'pg'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sport
    #      - POSTGRES_USER: postgres
    #      - 'POSTGRES_PASSWORD:root'
    #      - 'POSTGRES_DB:postgres'
    restart: always
  app:
    build: ./
#    image: docker-hub-dirol/app:latest
    container_name: 'myApp'
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgresdb
    restart: always